#!/usr/bin/env bash
# NexaFlow VPS bootstrap — run ONCE on a fresh Hostinger VPS as root.
#
# Idempotent: re-running won't hurt. It installs Docker if missing,
# clones the repo if missing, prompts for env values, and brings the
# stack up.
#
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/Dropdead6420/whatsapp-api/codex/nexaflow-v2-platform/deploy/vps/bootstrap.sh | bash
# or, after cloning:
#   cd /opt/nexaflow/whatsapp-api/deploy/vps && bash bootstrap.sh

set -euo pipefail

REPO_URL="https://github.com/Dropdead6420/whatsapp-api.git"
REPO_BRANCH="codex/nexaflow-v2-platform"
INSTALL_DIR="/opt/nexaflow"
APP_DIR="$INSTALL_DIR/whatsapp-api"
DEPLOY_DIR="$APP_DIR/deploy/vps"

# ---------- helpers ----------------------------------------------------------

log()  { printf "\033[1;32m▸ %s\033[0m\n" "$*"; }
warn() { printf "\033[1;33m! %s\033[0m\n" "$*"; }
die()  { printf "\033[1;31m✗ %s\033[0m\n" "$*" >&2; exit 1; }

require_root() {
  if [ "$(id -u)" -ne 0 ]; then
    die "Run as root (or via sudo). Current UID: $(id -u)"
  fi
}

prompt() {
  # prompt LABEL VAR [DEFAULT]
  local label="$1"
  local var="$2"
  local default="${3:-}"
  local value
  if [ -n "$default" ]; then
    read -r -p "$label [$default]: " value
    value="${value:-$default}"
  else
    while [ -z "${value:-}" ]; do
      read -r -p "$label: " value
    done
  fi
  printf -v "$var" '%s' "$value"
}

generate_secret() { openssl rand -base64 32 | tr -d '=' | tr -d '\n'; }

# ---------- 1. host packages --------------------------------------------------

install_host_packages() {
  log "Installing host packages (curl, git, openssl, ufw)"
  apt-get update -qq
  apt-get install -y -qq curl git openssl ufw ca-certificates >/dev/null
}

# ---------- 2. docker --------------------------------------------------------

install_docker_if_missing() {
  if command -v docker >/dev/null 2>&1 && docker compose version >/dev/null 2>&1; then
    log "Docker + compose already installed"
    return
  fi
  log "Installing Docker via get.docker.com"
  curl -fsSL https://get.docker.com | sh
  systemctl enable --now docker
}

# ---------- 3. firewall ------------------------------------------------------

configure_firewall() {
  log "Configuring UFW (22, 80, 443)"
  ufw --force reset >/dev/null
  ufw default deny incoming >/dev/null
  ufw default allow outgoing >/dev/null
  ufw allow 22/tcp >/dev/null
  ufw allow 80/tcp >/dev/null
  ufw allow 443/tcp >/dev/null
  ufw --force enable >/dev/null
}

# ---------- 4. clone or update -----------------------------------------------

clone_or_update_repo() {
  mkdir -p "$INSTALL_DIR"
  if [ -d "$APP_DIR/.git" ]; then
    log "Repo already cloned at $APP_DIR — fetching latest"
    git -C "$APP_DIR" fetch origin "$REPO_BRANCH"
    git -C "$APP_DIR" checkout "$REPO_BRANCH"
    git -C "$APP_DIR" reset --hard "origin/$REPO_BRANCH"
  else
    log "Cloning repo into $APP_DIR"
    git clone --branch "$REPO_BRANCH" --depth 1 "$REPO_URL" "$APP_DIR"
  fi
}

# ---------- 5. env file -------------------------------------------------------

create_env_file() {
  local env_file="$DEPLOY_DIR/.env.production"
  if [ -f "$env_file" ]; then
    log ".env.production already exists — keeping it (delete it to regenerate)"
    return
  fi

  log "Generating .env.production interactively"

  local DOMAIN_API DOMAIN_WEB POSTGRES_PASSWORD JWT_SECRET TENANT_TOKEN_ENCRYPTION_KEY
  local META_APP_ID META_APP_SECRET WHATSAPP_WEBHOOK_TOKEN
  local META_PHONE_NUMBER_ID META_BUSINESS_ACCOUNT_ID
  local ANTHROPIC_API_KEY OPENAI_API_KEY SENTRY_DSN

  prompt "Web domain (apex — e.g. medscrub.in)" DOMAIN_WEB
  prompt "API domain (e.g. api.${DOMAIN_WEB})" DOMAIN_API "api.${DOMAIN_WEB}"

  POSTGRES_PASSWORD="$(generate_secret)"
  JWT_SECRET="$(generate_secret)"
  TENANT_TOKEN_ENCRYPTION_KEY="$(generate_secret)"
  log "Generated POSTGRES_PASSWORD / JWT_SECRET / TENANT_TOKEN_ENCRYPTION_KEY"

  prompt "META_APP_ID (Enter to skip = 'placeholder')" META_APP_ID "placeholder"
  prompt "META_APP_SECRET (Enter to skip = 'placeholder')" META_APP_SECRET "placeholder"
  prompt "WHATSAPP_WEBHOOK_TOKEN (any random string)" WHATSAPP_WEBHOOK_TOKEN "$(openssl rand -hex 16)"
  prompt "META_PHONE_NUMBER_ID (Enter to skip)" META_PHONE_NUMBER_ID ""
  prompt "META_BUSINESS_ACCOUNT_ID (Enter to skip)" META_BUSINESS_ACCOUNT_ID ""
  prompt "ANTHROPIC_API_KEY (Enter to skip — disables AI features)" ANTHROPIC_API_KEY ""
  prompt "OPENAI_API_KEY (Enter to skip — disables KB OpenAI embeddings)" OPENAI_API_KEY ""
  prompt "SENTRY_DSN (Enter to skip — disables error reporting)" SENTRY_DSN ""

  cat > "$env_file" <<EOF
# Generated by bootstrap.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# DO NOT COMMIT. The repo .gitignore excludes .env* but be careful.

DOMAIN_API=$DOMAIN_API
DOMAIN_WEB=$DOMAIN_WEB
IMAGE_TAG=codex-nexaflow-v2-platform

POSTGRES_PASSWORD=$POSTGRES_PASSWORD
JWT_SECRET=$JWT_SECRET
TENANT_TOKEN_ENCRYPTION_KEY=$TENANT_TOKEN_ENCRYPTION_KEY

META_APP_ID=$META_APP_ID
META_APP_SECRET=$META_APP_SECRET
WHATSAPP_WEBHOOK_TOKEN=$WHATSAPP_WEBHOOK_TOKEN
META_PHONE_NUMBER_ID=$META_PHONE_NUMBER_ID
META_BUSINESS_ACCOUNT_ID=$META_BUSINESS_ACCOUNT_ID

ANTHROPIC_API_KEY=$ANTHROPIC_API_KEY
OPENAI_API_KEY=$OPENAI_API_KEY
SENTRY_DSN=$SENTRY_DSN
EOF

  chmod 600 "$env_file"
  log "Wrote $env_file (mode 600)"
}

# ---------- 6. bring stack up ------------------------------------------------

bring_up_stack() {
  log "Pulling API image from GHCR (web is built locally; see below)"
  # `pull` only fetches images that have a pre-built image:tag reference.
  # The web service uses `build:` so it's not pulled — we'll build it
  # next. --ignore-pull-failures lets the api+postgres+redis+caddy pulls
  # succeed even if (e.g.) GHCR rate-limits or the branch tag is moving.
  (cd "$DEPLOY_DIR" && docker compose -f docker-compose.prod.yml --env-file .env.production pull --ignore-pull-failures)

  log "Building web image locally (bakes NEXT_PUBLIC_API_URL into the bundle)"
  # First build takes ~5 min on a fresh VPS; subsequent builds are ~60s
  # thanks to Docker layer caching.
  (cd "$DEPLOY_DIR" && docker compose -f docker-compose.prod.yml --env-file .env.production build web)

  log "Starting the stack"
  (cd "$DEPLOY_DIR" && docker compose -f docker-compose.prod.yml --env-file .env.production up -d)
}

# ---------- 7. db migrations -------------------------------------------------

run_migrations() {
  log "Waiting for Postgres to be healthy"
  local tries=0
  until (cd "$DEPLOY_DIR" && docker compose -f docker-compose.prod.yml exec -T postgres pg_isready -U nexaflow -d nexaflow >/dev/null 2>&1); do
    tries=$((tries + 1))
    if [ "$tries" -gt 30 ]; then
      die "Postgres didn't come up within 60s. Check: docker compose -f $DEPLOY_DIR/docker-compose.prod.yml logs postgres"
    fi
    sleep 2
  done

  log "Running Prisma migrations"
  (cd "$DEPLOY_DIR" && docker compose -f docker-compose.prod.yml --env-file .env.production run --rm api \
    node node_modules/prisma/build/index.js migrate deploy \
    --schema packages/db/prisma/schema.prisma)
}

# ---------- 8. summary -------------------------------------------------------

print_summary() {
  local domain_api domain_web
  domain_api="$(grep '^DOMAIN_API=' "$DEPLOY_DIR/.env.production" | cut -d= -f2)"
  domain_web="$(grep '^DOMAIN_WEB=' "$DEPLOY_DIR/.env.production" | cut -d= -f2)"

  log "Done. Open these in your browser:"
  echo "  Web:   https://$domain_web"
  echo "  API:   https://$domain_api/api/v1/ready"
  echo
  log "Or curl-check from your laptop:"
  echo "  curl -i https://$domain_web/"
  echo "  curl -i https://$domain_api/live"
  echo "  curl -i https://$domain_api/api/v1/ready"
  echo
  log "Tail logs:"
  echo "  cd $DEPLOY_DIR && docker compose -f docker-compose.prod.yml logs -f api web worker"
  echo
  log "Update later (after you push code):"
  echo "  cd $DEPLOY_DIR && git -C /opt/nexaflow/whatsapp-api pull && \\"
  echo "    docker compose -f docker-compose.prod.yml --env-file .env.production pull --ignore-pull-failures && \\"
  echo "    docker compose -f docker-compose.prod.yml --env-file .env.production build web && \\"
  echo "    docker compose -f docker-compose.prod.yml --env-file .env.production up -d"
}

# ---------- main -------------------------------------------------------------

main() {
  require_root
  install_host_packages
  install_docker_if_missing
  configure_firewall
  clone_or_update_repo
  create_env_file
  bring_up_stack
  run_migrations
  print_summary
}

main "$@"
