import { prisma } from "@nexaflow/db";
import {
  ApiError,
  ErrorCodes,
  TenantType,
  TenantStatus,
  UserRole,
  LeadStatus,
} from "@nexaflow/shared";
import { authService } from "./auth.service";

const hashPassword = (pw: string) => authService.hashPassword(pw);

/**
 * Demo Service - Create, manage, and cleanup demo/sandbox tenants
 * 
 * Purpose: Partners can provision temporary demo environments to showcase features
 * to prospective customers. Demos auto-expire and can be renewed up to 2x.
 * 
 * Multi-tenancy: All demos scoped by parentTenantId (the partner who created it)
 * Security: Requires PARTNER_ADMIN or SUPER_ADMIN role
 */

/**
 * Optional blueprint payload that replaces the canned five-contact seed
 * with a brief-tailored set generated by the AI Demo Builder. The shape
 * is intentionally narrow so it can be JSON-serialized across the API
 * boundary and validated with Zod in the route layer.
 */
export interface DemoSeedPlan {
  industry?: string;
  contacts?: Array<{
    name: string;
    phoneNumber: string;
    email?: string;
    tags?: string[];
  }>;
  templates?: Array<{
    name: string;
    bodyText: string;
    category?: "MARKETING" | "UTILITY" | "AUTHENTICATION";
    headerText?: string;
    footerText?: string;
    language?: string;
  }>;
  campaignName?: string;
  leadTitle?: string;
  leadValue?: number;
  agentPersona?: {
    name: string;
    role: string;
    systemPrompt: string;
  };
  welcomeMessage?: string;
}

interface CreateDemoInput {
  partnerTenantId: string;
  demoName?: string;
  expiryDays?: number;
  seedPlan?: DemoSeedPlan;
}

interface DemoTenantInfo {
  tenantId: string;
  demoTenantId: string;
  demoUrl: string;
  expiresAt: Date;
  credentials: {
    email: string;
    password: string;
  };
  renewalCount: number;
}

/**
 * Create a new demo tenant with sample data
 * - Creates a new Tenant (type: BUSINESS, parent: partner)
 * - Seeds sample contacts, templates, campaign
 * - Creates demo user account
 * - Logs action to audit trail
 */
export async function createDemoTenant(
  input: CreateDemoInput
): Promise<DemoTenantInfo> {
  const {
    partnerTenantId,
    demoName = "Demo Workspace",
    expiryDays = 30,
    seedPlan,
  } = input;
  const partner = await prisma.tenant.findUnique({
    where: { id: partnerTenantId },
    select: { id: true, type: true, status: true },
  });

  if (!partner) {
    throw new ApiError(ErrorCodes.NOT_FOUND, 404, "Partner tenant not found.");
  }

  if (partner.type !== TenantType.WHITE_LABEL && partner.type !== TenantType.DIRECT) {
    throw new ApiError(
      ErrorCodes.FORBIDDEN,
      403,
      "Only WHITE_LABEL or DIRECT tenants can create demos."
    );
  }

  if (partner.status !== TenantStatus.ACTIVE) {
    throw new ApiError(ErrorCodes.FORBIDDEN, 403, "Partner tenant is not active.");
  }

  // Calculate expiry
  const expiresAt = new Date();
  expiresAt.setDate(expiresAt.getDate() + expiryDays);

  try {
    // Create demo tenant in transaction to ensure atomicity
    const result = await prisma.$transaction(async (tx) => {
      // 1. Create demo tenant
      const demoTenant = await tx.tenant.create({
        data: {
          name: demoName,
          type: TenantType.BUSINESS,
          status: TenantStatus.ACTIVE,
          parentTenantId: partnerTenantId,
          messageQuotaPerMonth: 1000, // Lower quota for demo
          contactLimit: 100,
          agentLimit: 2,
          aiCreditsPerMonth: 100,
          campaignLimit: 10,
        },
      });

      // 2. Create demo tracking record
      const demoRecord = await tx.demoTenant.create({
        data: {
          tenantId: demoTenant.id,
          createdByPartnerId: partnerTenantId,
          expiresAt,
        },
      });

      // 3. Create demo user (admin role)
      const demoEmail = `demo-${demoTenant.id.slice(0, 8)}@demo.nexaflow.local`;
      const demoPassword = generateSecurePassword();
      const hashedPassword = await hashPassword(demoPassword);

      await tx.user.create({
        data: {
          tenantId: demoTenant.id,
          email: demoEmail,
          password: hashedPassword,
          name: "Demo Admin",
          role: UserRole.BUSINESS_ADMIN,
          emailVerified: new Date(),
          status: "ACTIVE",
        },
      });

      // 4. Seed sample data — blueprint when provided, canned otherwise.
      if (seedPlan) {
        await seedBlueprintData(tx, demoTenant.id, seedPlan);
      } else {
        await seedDemoData(tx, demoTenant.id);
      }

      return {
        tenantId: demoTenant.id,
        demoTenantId: demoRecord.id,
        demoEmail,
        demoPassword,
        expiresAt,
      };
    });

    return {
      tenantId: result.tenantId,
      demoTenantId: result.demoTenantId,
      demoUrl: `https://demo-${result.tenantId.slice(0, 8)}.nexaflow.local/login`,
      expiresAt: result.expiresAt,
      credentials: {
        email: result.demoEmail,
        password: result.demoPassword,
      },
      renewalCount: 0,
    };
  } catch (error) {
    if (error instanceof ApiError) throw error;
    throw new ApiError(
      ErrorCodes.INTERNAL_SERVER_ERROR,
      500,
      "Failed to create demo tenant."
    );
  }
}

/**
 * Renew a demo tenant (extend expiry)
 * - Can renew max 2x (total 3 x 30 days = 90 days max)
 * - Updates expiresAt and lastRenewedAt
 */
export async function renewDemoTenant(
  demoTenantId: string,
  expiryDays: number = 30
): Promise<{ expiresAt: Date; renewalCount: number }> {
  const demoTenant = await prisma.demoTenant.findUnique({
    where: { id: demoTenantId },
  });

  if (!demoTenant) {
    throw new ApiError(ErrorCodes.NOT_FOUND, 404, "Demo tenant not found.");
  }

  if (demoTenant.renewalCount >= 2) {
    throw new ApiError(
      ErrorCodes.QUOTA_EXCEEDED,
      400,
      "Demo has reached maximum renewal count (2x). Please create a new demo."
    );
  }

  const newExpiresAt = new Date();
  newExpiresAt.setDate(newExpiresAt.getDate() + expiryDays);

  const updated = await prisma.demoTenant.update({
    where: { id: demoTenantId },
    data: {
      expiresAt: newExpiresAt,
      renewalCount: { increment: 1 },
      lastRenewedAt: new Date(),
    },
  });

  return {
    expiresAt: updated.expiresAt,
    renewalCount: updated.renewalCount,
  };
}

/**
 * Delete a demo tenant immediately
 * - Cascade deletes all related data (users, contacts, campaigns, etc.)
 * - Removes DemoTenant record
 */
export async function deleteDemoTenant(demoTenantId: string): Promise<void> {
  const demoTenant = await prisma.demoTenant.findUnique({
    where: { id: demoTenantId },
  });

  if (!demoTenant) {
    throw new ApiError(ErrorCodes.NOT_FOUND, 404, "Demo tenant not found.");
  }

  try {
    // Delete tenant (cascade will delete DemoTenant)
    await prisma.tenant.delete({
      where: { id: demoTenant.tenantId },
    });
  } catch (error) {
    throw new ApiError(
      ErrorCodes.INTERNAL_SERVER_ERROR,
      500,
      "Failed to delete demo tenant."
    );
  }
}

/**
 * Get demo tenant info
 */
export async function getDemoTenant(demoTenantId: string) {
  const demo = await prisma.demoTenant.findUnique({
    where: { id: demoTenantId },
    include: {
      tenant: {
        select: {
          id: true,
          name: true,
          status: true,
          createdAt: true,
          _count: {
            select: {
              contacts: true,
              campaigns: true,
              users: true,
            },
          },
        },
      },
    },
  });

  if (!demo) {
    throw new ApiError(ErrorCodes.NOT_FOUND, 404, "Demo tenant not found.");
  }

  return demo;
}

/**
 * List all demo tenants created by a partner
 */
export async function listPartnerDemos(
  partnerTenantId: string,
  page: number = 1,
  limit: number = 25
) {
  const skip = (page - 1) * limit;

  const [demos, total] = await Promise.all([
    prisma.demoTenant.findMany({
      where: { createdByPartnerId: partnerTenantId },
      include: {
        tenant: {
          select: {
            name: true,
            status: true,
            _count: { select: { contacts: true, users: true } },
          },
        },
      },
      skip,
      take: limit,
      orderBy: { createdAt: "desc" },
    }),
    prisma.demoTenant.count({
      where: { createdByPartnerId: partnerTenantId },
    }),
  ]);

  return {
    demos,
    pagination: {
      page,
      limit,
      total,
      pages: Math.ceil(total / limit),
    },
  };
}

/**
 * Cleanup expired demo tenants (called by background worker)
 */
export async function cleanupExpiredDemos(): Promise<{ deleted: number }> {
  const now = new Date();

  const expired = await prisma.demoTenant.findMany({
    where: {
      expiresAt: { lte: now },
    },
    select: { tenantId: true },
  });

  let deleted = 0;
  for (const demo of expired) {
    try {
      await prisma.tenant.delete({
        where: { id: demo.tenantId },
      });
      deleted++;
    } catch (error) {
      console.error(
        `Failed to delete expired demo tenant ${demo.tenantId}:`,
        error
      );
    }
  }

  return { deleted };
}

// ============================================================================
// INTERNAL HELPERS
// ============================================================================

/**
 * Seed demo tenant with sample data
 */
async function seedDemoData(
  tx: any, // Prisma transaction client
  tenantId: string
): Promise<void> {
  // 1. Create sample contacts
  const sampleContacts = [
    {
      tenantId,
      firstName: "Alice",
      lastName: "Johnson",
      email: "alice@example.com",
      phoneNumber: "+14155552671",
      source: "DEMO",
    },
    {
      tenantId,
      firstName: "Bob",
      lastName: "Smith",
      email: "bob@example.com",
      phoneNumber: "+14155552672",
      source: "DEMO",
    },
    {
      tenantId,
      firstName: "Charlie",
      lastName: "Brown",
      email: "charlie@example.com",
      phoneNumber: "+14155552673",
      source: "DEMO",
    },
    {
      tenantId,
      firstName: "Diana",
      lastName: "Prince",
      email: "diana@example.com",
      phoneNumber: "+14155552674",
      source: "DEMO",
    },
    {
      tenantId,
      firstName: "Eve",
      lastName: "Wilson",
      email: "eve@example.com",
      phoneNumber: "+14155552675",
      source: "DEMO",
    },
  ];

  const contacts = await Promise.all(
    sampleContacts.map(({ firstName, lastName, source, ...contact }) =>
      tx.contact.create({
        data: {
          ...contact,
          name: `${firstName} ${lastName}`,
          tags: [source.toLowerCase()],
        },
      })
    )
  );

  // 2. Create sample template
  const template = await tx.whatsAppTemplate.create({
    data: {
      tenantId,
      name: "welcome_demo",
      bodyText: "Hello {{name}}, welcome to our NexaFlow demo.",
      status: "APPROVED",
      headerText: "Welcome",
      footerText: "Demo Message",
      language: "en",
      category: "MARKETING",
      variants: [],
    },
  });

  // 3. Create sample campaign
  await tx.campaign.create({
    data: {
      tenantId,
      name: "Demo Campaign",
      description: "Sample campaign for demonstration",
      type: "BROADCAST",
      status: "DRAFT",
      templateId: template.id,
      targetContacts: JSON.stringify({
        mode: "contacts",
        contactIds: contacts.map((contact: { id: string }) => contact.id),
      }),
      totalContacts: contacts.length,
    },
  });

  // 4. Create sample lead
  const leadContact = contacts[0];
  await tx.lead.create({
    data: {
      tenantId,
      contactId: leadContact.id,
      title: "Sample demo lead",
      description: "A seeded opportunity for partners to show the lead pipeline.",
      status: LeadStatus.NEW,
      value: 25000,
      probability: 0.35,
    },
  });
}

/**
 * Seed demo tenant from an AI-generated blueprint. Mirrors seedDemoData
 * but uses the brief-tailored contacts / templates / campaign / lead the
 * partner has approved. Falls back to defaults for each missing field so
 * a partial blueprint never produces an empty demo.
 */
async function seedBlueprintData(
  tx: any, // Prisma transaction client
  tenantId: string,
  plan: DemoSeedPlan,
): Promise<void> {
  // ----- Contacts ---------------------------------------------------------
  const contactSeeds =
    plan.contacts && plan.contacts.length > 0
      ? plan.contacts.slice(0, 25)
      : [
          {
            name: "Alex Sample",
            phoneNumber: "+14155550100",
            email: "alex@example.com",
            tags: ["demo"],
          },
          {
            name: "Sam Sample",
            phoneNumber: "+14155550101",
            email: "sam@example.com",
            tags: ["demo"],
          },
        ];

  const contacts = await Promise.all(
    contactSeeds.map((c) =>
      tx.contact.create({
        data: {
          tenantId,
          name: c.name,
          phoneNumber: c.phoneNumber,
          email: c.email ?? null,
          tags: (c.tags && c.tags.length > 0 ? c.tags : ["demo"]).slice(0, 8),
        },
      }),
    ),
  );

  // ----- Templates --------------------------------------------------------
  const templateSeeds =
    plan.templates && plan.templates.length > 0
      ? plan.templates.slice(0, 10)
      : [
          {
            name: "welcome_demo",
            bodyText: plan.welcomeMessage ?? "Hello {{1}}, welcome to our demo workspace.",
            category: "MARKETING" as const,
            headerText: "Welcome",
            footerText: "Demo",
            language: "en",
          },
        ];

  const templates = await Promise.all(
    templateSeeds.map((t, idx) =>
      tx.whatsAppTemplate.create({
        data: {
          tenantId,
          name:
            (t.name || `demo_template_${idx + 1}`).replace(/[^a-z0-9_]/gi, "_").toLowerCase(),
          bodyText: t.bodyText,
          status: "APPROVED",
          headerText: t.headerText ?? null,
          footerText: t.footerText ?? null,
          language: t.language ?? "en",
          category: t.category ?? "MARKETING",
          variants: [],
        },
      }),
    ),
  );

  // ----- Campaign ---------------------------------------------------------
  const primaryTemplate = templates[0];
  if (primaryTemplate) {
    await tx.campaign.create({
      data: {
        tenantId,
        name: plan.campaignName ?? "Demo broadcast",
        description:
          plan.industry
            ? `Sample broadcast tailored for ${plan.industry}.`
            : "Sample broadcast for the demo workspace.",
        type: "BROADCAST",
        status: "DRAFT",
        templateId: primaryTemplate.id,
        targetContacts: JSON.stringify({
          mode: "contacts",
          contactIds: contacts.map((c: { id: string }) => c.id),
        }),
        totalContacts: contacts.length,
      },
    });
  }

  // ----- Lead -------------------------------------------------------------
  const leadContact = contacts[0];
  if (leadContact) {
    await tx.lead.create({
      data: {
        tenantId,
        contactId: leadContact.id,
        title: plan.leadTitle ?? "Sample demo opportunity",
        description:
          plan.industry
            ? `Pipeline example for a ${plan.industry} prospect.`
            : "Pipeline example so partners can demonstrate the deal flow.",
        status: LeadStatus.NEW,
        value: Math.max(0, Math.min(plan.leadValue ?? 25_000, 10_000_000)),
        probability: 0.35,
      },
    });
  }

  // ----- AI agent persona -------------------------------------------------
  // Best-effort: skip silently if the agent persona is missing or the
  // model rejects it — the demo still works without a default agent.
  if (plan.agentPersona && plan.agentPersona.systemPrompt) {
    try {
      await tx.aiAgent.create({
        data: {
          tenantId,
          name: plan.agentPersona.name.slice(0, 120) || "Demo Agent",
          description: plan.agentPersona.role.slice(0, 240),
          systemPrompt: plan.agentPersona.systemPrompt.slice(0, 4000),
          status: "ACTIVE",
          isDefault: true,
        },
      });
    } catch (err) {
      console.warn("[demo-blueprint] failed to seed AI agent persona:", err);
    }
  }
}

/**
 * Generate a secure random password
 */
function generateSecurePassword(): string {
  const chars =
    "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!@#$%";
  let password = "";
  for (let i = 0; i < 16; i++) {
    password += chars.charAt(Math.floor(Math.random() * chars.length));
  }
  return password;
}
