// ============================================================================
// Invoice PDF renderer (Claude FINAL §4, slice 12)
//
// Builds the PDF binary for a single invoice. Two modes:
//
//   1. pdfkit available → real PDF with proper headers, A4 page,
//      tenant name, invoice number, line item table, totals.
//   2. pdfkit not installed → minimal hand-built valid PDF with a
//      plain-text "summary" body. Still a valid application/pdf
//      file (browsers preview it); just unstyled.
//
// The dynamic-import + try/catch shape mirrors the auto-recharge
// service's stub mode — keeps the codebase testable without
// requiring the dep to be installed in every environment.
// ============================================================================

import type { Invoice } from "@nexaflow/db";

interface InvoiceRenderInput {
  invoice: Invoice;
  tenantName?: string | null;
  /** Issuer name shown on the invoice. Defaults to "NexaFlow AI". */
  issuerName?: string;
}

/**
 * Returns the rendered PDF as a Buffer. Never throws — falls back
 * to the stub renderer when pdfkit isn't reachable.
 */
export async function renderInvoicePdf(
  input: InvoiceRenderInput,
): Promise<Buffer> {
  try {
    return await renderWithPdfkit(input);
  } catch (err) {
    console.warn(
      "[invoice-pdf] pdfkit unavailable, falling back to text stub:",
      (err as Error).message,
    );
    return renderTextStubPdf(input);
  }
}

// ---- pdfkit branch --------------------------------------------------------

async function renderWithPdfkit(input: InvoiceRenderInput): Promise<Buffer> {
  // Dynamic import so build / tests don't blow up when the dep
  // isn't installed in the sandbox / CI matrix. The module specifier
  // is intentionally constructed at runtime so tsc doesn't try to
  // resolve types statically (pdfkit ships no first-party types).
  const specifier = "pdfkit";
  const mod = (await import(/* @vite-ignore */ specifier)) as {
    default: new (opts?: Record<string, unknown>) => PdfkitDocLike;
  };
  const PDFDocument = mod.default;

  return new Promise<Buffer>((resolve, reject) => {
    const doc = new PDFDocument({ size: "A4", margin: 50 });
    const chunks: Buffer[] = [];
    doc.on("data", (c: Buffer) => chunks.push(c));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", (e: Error) => reject(e));

    const inv = input.invoice;
    const issuer = input.issuerName ?? "NexaFlow AI";
    const tenant = input.tenantName ?? inv.tenantId;
    const major = inv.amountInPaisa / 100;
    const subtotal = inv.subtotalInPaisa / 100;
    const tax = inv.taxInPaisa / 100;

    doc.fontSize(20).text(issuer, { align: "right" });
    doc.fontSize(10).text("Wallet recharge invoice", { align: "right" });
    doc.moveDown();

    doc.fontSize(14).text(`Invoice ${inv.invoiceNumber}`);
    doc
      .fontSize(10)
      .text(
        `Issued ${new Date(inv.createdAt).toLocaleDateString()}` +
          (inv.paidAt
            ? ` · Paid ${new Date(inv.paidAt).toLocaleDateString()}`
            : ""),
      );
    doc.moveDown();

    doc.fontSize(11).text(`Billed to: ${tenant}`);
    doc.text(`Tenant id: ${inv.tenantId}`);
    if (inv.paymentOrderId) doc.text(`Payment order: ${inv.paymentOrderId}`);
    if (inv.rechargeRequestId)
      doc.text(`Recharge request: ${inv.rechargeRequestId}`);
    doc.moveDown();

    // Single line item — recharge invoices only ever have one row.
    doc.fontSize(11).text(`Wallet recharge`, 50, doc.y);
    doc.text(`${inv.currency} ${subtotal.toFixed(2)}`, { align: "right" });
    if (tax > 0) {
      doc.text(`Tax`, 50, doc.y);
      doc.text(`${inv.currency} ${tax.toFixed(2)}`, { align: "right" });
    }
    doc.moveDown();
    doc.fontSize(12).text(`Total`, 50, doc.y);
    doc.text(`${inv.currency} ${major.toFixed(2)}`, { align: "right" });

    doc.moveDown(2);
    doc
      .fontSize(8)
      .fillColor("#666")
      .text(
        "Generated by NexaFlow AI. Questions about this invoice? Contact your account manager.",
        { align: "center" },
      );

    doc.end();
  });
}

interface PdfkitDocLike {
  fontSize(size: number): PdfkitDocLike;
  text(value: string, ...rest: unknown[]): PdfkitDocLike;
  moveDown(lines?: number): PdfkitDocLike;
  fillColor(color: string): PdfkitDocLike;
  on(event: "data", cb: (chunk: Buffer) => void): void;
  on(event: "end", cb: () => void): void;
  on(event: "error", cb: (err: Error) => void): void;
  end(): void;
  y: number;
}

// ---- Fallback: minimal valid PDF -----------------------------------------

/**
 * Returns a minimal valid 1-page PDF whose content stream is the
 * plain-text summary of the invoice. Browsers preview it as a real
 * PDF; readers see the invoice info; pdf-validators accept it as
 * PDF/1.4.
 *
 * The format is *intentionally simple* — we generate the xref table
 * by computing byte offsets after assembling the body. This is the
 * documented "hello world" of PDF — no fonts beyond the built-in
 * Type1 Helvetica.
 */
function renderTextStubPdf(input: InvoiceRenderInput): Buffer {
  const lines = buildStubBodyLines(input);
  const content = `BT /F1 11 Tf 50 780 Td 14 TL ${lines
    .map((l, i) => (i === 0 ? `(${l}) Tj` : `T* (${l}) Tj`))
    .join(" ")} ET`;

  // Build PDF object bytes piece by piece so we can stamp the xref
  // offsets correctly.
  const objects: string[] = [];

  objects.push("1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n");
  objects.push("2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj\n");
  objects.push(
    "3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>\nendobj\n",
  );
  objects.push(
    "4 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>\nendobj\n",
  );
  objects.push(
    `5 0 obj\n<< /Length ${Buffer.byteLength(content, "utf-8")} >>\nstream\n${content}\nendstream\nendobj\n`,
  );

  // Compute xref offsets.
  const header = "%PDF-1.4\n";
  let cursor = Buffer.byteLength(header, "utf-8");
  const offsets: number[] = [];
  for (const obj of objects) {
    offsets.push(cursor);
    cursor += Buffer.byteLength(obj, "utf-8");
  }
  const xrefStart = cursor;
  const xref =
    `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n` +
    offsets
      .map((o) => `${String(o).padStart(10, "0")} 00000 n \n`)
      .join("") +
    `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefStart}\n%%EOF\n`;

  return Buffer.from(header + objects.join("") + xref, "utf-8");
}

/**
 * Plain-text rendering of the invoice — used as the stub PDF body.
 * Exported for tests so the human-readable shape is pinned.
 */
export function buildStubBodyLines(input: InvoiceRenderInput): string[] {
  const inv = input.invoice;
  const issuer = input.issuerName ?? "NexaFlow AI";
  const tenant = input.tenantName ?? inv.tenantId;
  const major = inv.amountInPaisa / 100;
  return [
    `${issuer} — Wallet recharge invoice`,
    `Invoice: ${inv.invoiceNumber}`,
    `Date: ${new Date(inv.createdAt).toISOString().slice(0, 10)}`,
    `Billed to: ${tenant} (tenant ${inv.tenantId})`,
    `Total: ${inv.currency} ${major.toFixed(2)}`,
    inv.paymentOrderId ? `Payment order: ${inv.paymentOrderId}` : "",
    inv.rechargeRequestId ? `Recharge request: ${inv.rechargeRequestId}` : "",
  ].filter(Boolean);
}
